/*
Antilua
Copyright (C) 2020 Elias Fleckenstein <eliasfleckenstein@web.de>

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation; either version 2.1 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License along
with this program; if not, write to the Free Software Foundation, Inc.,
51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
*/

#pragma once

#include "overlayPanel.h"
#include "client/client.h"
#include "script/scripting_client.h"
#include <map>

extern class CheatMenu *g_cheat_menu;
extern bool g_cheat_layer_active;
extern bool g_cheat_layer_force_hidden;
extern bool g_quick_palette_active;
extern bool g_show_minimal_debug;

#define CHEAT_MENU_GET_SCRIPTPTR                                                         \
	ClientScripting *script = m_client->getScript();                                 \
	if (!script || !script->m_cheats_loaded)                                         \
		return;

#define CHEAT_MENU_GET_SCRIPTPTR_RET(retval)                                             \
	ClientScripting *script = m_client->getScript();                                 \
	if (!script || !script->m_cheats_loaded)                                         \
		return retval;

// One row in the Quick Access Palette. Either a cheat toggle (CHEAT) or an
// entry generated by a Lua list provider (LUA_ENTRY).
struct QuickPaletteItem
{
	enum class Kind : u8 { CHEAT, LUA_ENTRY };
	Kind kind = Kind::LUA_ENTRY;
	ScriptApiCheatsCheat *cheat = nullptr;
	std::string label;
	std::string description;
	std::string category;
	std::vector<std::string> keywords;
	std::string action_id;
	int action_ref = 0;
	int is_enabled_ref = 0;
	bool has_enabled_state = false;
	bool enabled_state = false;
	bool repeat_last = false;
	std::vector<std::string> toggle_settings;
};

class CheatMenu : public PanelOverlay
{
public:
	CheatMenu(Client *client);

	ClientScripting *getScript() { return m_client->getScript(); }

	void drawHUD(video::IVideoDriver *driver, double dtime);
	void drawAll(video::IVideoDriver *driver, v2s32 mouse_pos, bool show_debug) override;
	void handleMouse(v2s32 pos, bool left_down) override;
	void handleRightClick(v2s32 pos) override;

	void createCategoryPanels();
	void onLayerClosed();

	void selectUp();
	void selectDown();
	void selectLeft();
	void selectRight();
	void selectConfirm();

	void drawSearchBar(video::IVideoDriver *driver);
	bool pollInput();
	bool hasSearchText() const { return !m_search_text.empty(); }
	const std::string &getSearchText() const { return m_search_text; }

	// Supermenu
	void createSupermenuPanel();

	// Quick Access Palette
	void toggleQuickPalette();
	void openQuickPalette(const std::string &search);
	void drawQuickPalette(video::IVideoDriver *driver, v2s32 mouse_pos);
	void pollQuickPaletteInput();
	bool isQuickPaletteActive() const { return m_quick_palette_active; }
	void paletteUp();
	void paletteDown();
	void paletteConfirm();
	void paletteScroll(s32 wheel);
	void paletteClick(v2s32 pos);

	// Lua-accessible helpers for introspection / tests
	int getQuickMenuEntries(lua_State *L);
	int activateQuickMenuEntry(lua_State *L);

protected:
	void initPanels() override { createCategoryPanels(); }
	s32 getPanelContentHeight(const OverlayPanel &panel) override;
	void drawPanelContent(video::IVideoDriver *driver,
		OverlayPanel &panel, s32 content_x, s32 content_y,
		s32 content_w, s32 content_h, v2s32 mouse_pos) override;
	void handlePanelContentClick(size_t panel_idx, v2s32 pos, s32 cx, s32 cy, s32 cw) override;
	void autoTilePanels(v2u32 screen_size) override;

private:
	Client *m_client;

	video::SColor m_tooltip_bg;

	float m_rainbow_offset = 0.0;

	// Tooltip state
	std::string m_tooltip_text;
	s32 m_tooltip_x = 0, m_tooltip_y = 0;
	u64 m_hover_start = 0;

	// Search bar
	std::string m_search_text;

	// Quick Access Palette
	bool m_quick_palette_active = false;
	std::string m_quick_palette_text;
	int m_quick_palette_selected = 0;
	int m_quick_palette_scroll = 0;
	std::vector<QuickPaletteItem> m_quick_palette_items;
	std::map<std::string, int> m_quick_menu_usage;

	// Last activated Lua entry (for the "repeat last" row)
	bool m_quick_palette_last_valid = false;
	QuickPaletteItem m_quick_palette_last;

	void collectQuickPaletteItems();
	void clearQuickPaletteItems();
	void closeQuickPalette();
	void getFilteredPaletteItems(std::vector<QuickPaletteItem *> &out);
	void runQuickPaletteAction(const QuickPaletteItem &item);
	static const std::string &quickPaletteItemLabel(const QuickPaletteItem &item);
	void bumpQuickMenuUsage(const std::string &key);
	void updatePaletteScroll(int total);
	int quickPaletteVisibleCount() const;
	int paletteRowAt(v2s32 pos) const;
	void storeLastAction(const QuickPaletteItem &item);
	void clearLastAction();
	void runLastAction();
	void saveQuickMenuUsage();
	void loadQuickMenuUsage();

	// Supermenu
	int m_super_level = 0;
	int m_super_selected_category = 0;

	// Favorites
	bool isFavorite(const std::string &setting) const;
	void toggleFavorite(const std::string &setting);
	int countFavoritedCheats(ClientScripting *script) const;

	// Recently Used
	static constexpr size_t MAX_RECENT = 10;
	std::vector<std::string> m_recent_cheats;
	void addRecentCheat(const std::string &setting);
	void createRecentPanel();
	void loadRecentCheats();
	void saveRecentCheats();
	static bool isRecentPanel(const OverlayPanel &p);

	// Right-click context menu
	struct ContextMenuState {
		bool active = false;
		s32 x, y, w, h;
		int selected = 0;
		std::string cheat_setting;
		bool is_enabled = false;
		bool has_settings = false;
		bool is_favorite = false;
		int ctx_panel_idx = -1;  // >= 0 means panel-level (enable/disable all)
	};
	ContextMenuState m_ctx;
	void dismissContextMenu();
	void drawContextMenu(video::IVideoDriver *driver);
	void execContextMenu();
	bool handleContextMenuItemClick(v2s32 pos);

	// Profiles dropdown
	bool m_profiles_active = false;
	v2s32 m_profiles_pos;
	s32 m_profiles_selected = 0;
	std::vector<std::string> m_profile_names;
	void refreshProfileList();
	void loadProfile(size_t idx);
	void drawProfilesPopup(video::IVideoDriver *driver);

	// Quick slots
	int getSlotForSetting(const std::string &setting) const;

	// Conflicts
	bool hasActiveConflict(ScriptApiCheatsCheat *cheat) const;

	// Close cheat layer before opening a formspec from within the menu
	static void closeForFormspec();
};
